### ISSUE TITLE
Missing file during upload results in server crash/panic

### ISSUE THREAD

**Issue by JustinTimperio** [lu4p/ToRat#179]
```
[vBHv3Vc5awx39ivu] /$ cd /etc/
[vBHv3Vc5awx39ivu] /etc$ up fstab
[!] Upload failed could not Read file
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x896b3d]

goroutine 1 [running]:
github.com/JustinTimperio/ToRat/torat_server.(*activeClient).Upload(0xc0000de500, 0xc00031e000)
        /ToRat/torat_server/shell.go:346 +0x13d
github.com/abiosoft/ishell.(*Shell).handleCommand(0xc000370000, 0xc00010c980, 0x2, 0x2, 0xc0002cd728, 0x20, 0xc000000180)
        /go/pkg/mod/github.com/abiosoft/ishell@v2.0.0+incompatible/ishell.go:250 +0x322
github.com/abiosoft/ishell.handleInput(0xc000370000, 0xc00010c980, 0x2, 0x2, 0xc00022c601, 0xc000028660)
        /go/pkg/mod/github.com/abiosoft/ishell@v2.0.0+incompatible/ishell.go:204 +0x4d
github.com/abiosoft/ishell.(*Shell).run(0xc000370000)
        /go/pkg/mod/github.com/abiosoft/ishell@v2.0.0+incompatible/ishell.go:183 +0x22e
github.com/abiosoft/ishell.(*Shell).Run(0xc000370000)
        /go/pkg/mod/github.com/abiosoft/ishell@v2.0.0+incompatible/ishell.go:99 +0x39
github.com/JustinTimperio/ToRat/torat_server.activeClient.shellClient(0xc00010eef0, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00011aa20, 0xc00010eef0, 0x10, ...)
        /ToRat/torat_server/shell.go:201 +0xaf4
github.com/JustinTimperio/ToRat/torat_server.Shell.func1(0xc00031e4e0)
        /ToRat/torat_server/shell.go:45 +0x105
github.com/abiosoft/ishell.(*Shell).handleCommand(0xc0001b8d20, 0xc0000fd320, 0x1, 0x1, 0xc000171d60, 0x20, 0xc000000180)
        /go/pkg/mod/github.com/abiosoft/ishell@v2.0.0+incompatible/ishell.go:250 +0x322
github.com/abiosoft/ishell.handleInput(0xc0001b8d20, 0xc0000fd320, 0x1, 0x1, 0xc000408801, 0xc00043c3c0)
        /go/pkg/mod/github.com/abiosoft/ishell@v2.0.0+incompatible/ishell.go:204 +0x4d
github.com/abiosoft/ishell.(*Shell).run(0xc0001b8d20)
        /go/pkg/mod/github.com/abiosoft/ishell@v2.0.0+incompatible/ishell.go:183 +0x22e
github.com/abiosoft/ishell.(*Shell).Run(0xc0001b8d20)
        /go/pkg/mod/github.com/abiosoft/ishell@v2.0.0+incompatible/ishell.go:99 +0x39
github.com/JustinTimperio/ToRat/torat_server.Shell()
        /ToRat/torat_server/shell.go:113 +0x5bd
main.main()
        /ToRat/cmd/server/main.go:10 +0x3a
```

**Comment by JustinTimperio** [comment]
This issue was opened in duplicate accidentally. Please see issue #183
