### ISSUE TITLE
Client `up` command panic crashes on missing file

### ISSUE THREAD

**Issue by JustinTimperio** [lu4p/ToRat#183]
```
[vBHv3Vc5awx39ivu] /home/justin/Repos/Shell/nixinfo$ up ls
[Server] [!] Upload failed could not read local file!
[Server] [!] open ls: no such file or directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x895cce]

goroutine 1 [running]:
github.com/lu4p/ToRat/torat_server.(*activeClient).Upload(0xc00032e400, 0xc00049a1a0)
        /ToRat/torat_server/client_ishell.go:182 +0x14e
github.com/abiosoft/ishell.(*Shell).handleCommand(0xc000424000, 0xc0004be1e0, 0x2, 0x2, 0xc0000f56f8, 0x20, 0xc000000180)
        /go/pkg/mod/github.com/abiosoft/ishell@v2.0.0+incompatible/ishell.go:250 +0x322
github.com/abiosoft/ishell.handleInput(0xc000424000, 0xc0004be1e0, 0x2, 0x2, 0xc000247801, 0xc000270960)
        /go/pkg/mod/github.com/abiosoft/ishell@v2.0.0+incompatible/ishell.go:204 +0x4d
github.com/abiosoft/ishell.(*Shell).run(0xc000424000)
        /go/pkg/mod/github.com/abiosoft/ishell@v2.0.0+incompatible/ishell.go:183 +0x22e
github.com/abiosoft/ishell.(*Shell).Run(0xc000424000)
        /go/pkg/mod/github.com/abiosoft/ishell@v2.0.0+incompatible/ishell.go:99 +0x39
github.com/lu4p/ToRat/torat_server.activeClient.shellClient(0xc0003125d0, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000245740, 0xc0003125d0, 0x10, ...)
        /ToRat/torat_server/client_ishell.go:99 +0xd3d
github.com/lu4p/ToRat/torat_server.Shell.func1(0xc00031ac30)
        /ToRat/torat_server/server_ishell.go:38 +0x105
github.com/abiosoft/ishell.(*Shell).handleCommand(0xc0001d2d20, 0xc000314c80, 0x1, 0x1, 0xc0000f5d60, 0x20, 0xc000000180)
        /go/pkg/mod/github.com/abiosoft/ishell@v2.0.0+incompatible/ishell.go:250 +0x322
github.com/abiosoft/ishell.handleInput(0xc0001d2d20, 0xc000314c80, 0x1, 0x1, 0xc000314b01, 0xc000310360)
        /go/pkg/mod/github.com/abiosoft/ishell@v2.0.0+incompatible/ishell.go:204 +0x4d
github.com/abiosoft/ishell.(*Shell).run(0xc0001d2d20)
        /go/pkg/mod/github.com/abiosoft/ishell@v2.0.0+incompatible/ishell.go:183 +0x22e
github.com/abiosoft/ishell.(*Shell).Run(0xc0001d2d20)
        /go/pkg/mod/github.com/abiosoft/ishell@v2.0.0+incompatible/ishell.go:99 +0x39
github.com/lu4p/ToRat/torat_server.Shell()
        /ToRat/torat_server/server_ishell.go:108 +0x5bd
main.main()
        /ToRat/cmd/server/main.go:10 +0x3a
```

**Comment by JustinTimperio** [comment]
@lu4p This can be patched with commit https://github.com/JustinTimperio/ToRat/commit/af61c05e4013393042c74c051293cd639215d401
